version: "3.8"

services:
  eurekai_app:
    build: .
    container_name: eurekai_container
    restart: always
    ports:
      - "80:80"
    env_file:
      - .env # ✅ This ensures Docker loads your environment variables
    environment:
      - NODE_ENV=production
